### ISSUE TITLE
Unable to build image for Raspberry Pi 3 B+ due to raspi-firmware missing

### ISSUE THREAD

**Issue by ruben-s** [bashrc2/libreserver-maker#1]
Hi,

I failed to install Libreserver on a Raspberry, twice.

First I tried on a Raspberry Pi 4 based on https://libreserver.org/installation.html
However when writing the pi image to SD card, the Pi did not boot.
I then tried writing the imgage to a USB file and boot from USB, however this also failed: 
the Pi4 bootloader starts but then timeout on rootfs.
For some reason the rootfs partition does not get mounted (tried rewriting the usb twice).
(Oddly the usb is not recognizable nor mountable in a standard Ubuntu install, whilst I could mount the 2 partitions written to the SD card. Same image file.)

Then I found this project: libreserver-maker.
I tried to build libreserver for raspberry Pi 3 B+ (there is no specific Pi 4 option).
However the image build process fails:
>> "qemu: Unsupported syscall: 403\nE: Unable to find a source package for raspi-firmware\n"

I think this is due to the line 
'apt-get source {firmware_package}' where {firmware_package} = raspi-firmware in the file raspberry_pi_with_uboot.py.
a) some digging makes me suspect there is no source for raspi-firmware as it's closed source
(cfr.https://wiki.debian.org/RaspberryPi)
b) there exists a binary package for raspi-firmware: https://packages.debian.org/bullseye/raspi-firmware
However this is not available in sources.list.
I've added below lines to the raspberry_pi_with_uboot.py file
>>echo "deb http://ftp.de.debian.org/debian bullseye main non-free" | tee -a /etc/apt/sources.list
>>apt-get update

and changed 
>>"apt-get source {firmware_package}"  ->  "apt-get download {firmware_package}"

The raspi-firmware package is now downloaded however the layout in this deb package does not correspond to what is expected in the remainder of the script. So it still fails.

I'm stuck and I don't know enough about boot partitions, firmware loaders, debian, pi specifics, .... 

Any suggestions on how to continue?

Thx.

br,
 Ruben

**Comment by bashrc2** [comment]
I'm stuck and I don't know enough about boot partitions, firmware loaders, debian, pi specifics, ....

>
> Any suggestions on how to continue?
>
>
> Thx.
>
>
>
> br,
>  Ruben
>
>
>

I notice that the official Raspbian is now based on Debian 11, so I'll try making an image with that. If you need something quickly then try downloading the Raspbian lite version and then do a manual install.

https://libreserver.org/armbian.html

**Comment by ruben-s** [comment]
Hi bashrc2,

thanks for your reply.
I'm just back from holiday.
I spent some time to try your suggestion (i.e. https://libreserver.org/armbian.html).

Yet I seem to hit another obstacle.

I've installed Armbian Jammy and it failed: when I try to run "libreserver menuconfig --noninteractive"
I get the response:  "You should only run this on a Debian Buster based system"
This even though I checked out the branch/release bullseye (git checkout bullseye).

I checked and Armbian Jammy is the ubuntu 22.04 Jammy Jellyfish derivation (which is based on debian ??)

I then tried with Armbian Focal (which is the ubuntu 20.04 Focal derivation of Armbian, itself derived from debian bullseye).
But I get the same result: "You should only run this on a Debian Buster based system"
(see attached log below)

So, am I correct to understand that libreserver does not install on an ubuntu derived Armbian?
If so I'm out of luck as it seems that for my Raspberry Pi4 there is only Armbian support recently and from the names it appears to be based on ubuntu (i.e. Jammy, i.e. Ubuntu 22.04 and Focal, i.e. Ubuntu 20.04). cfr. https://imola.armbian.com/dl/rpi4b/
There is no Debian Buster based release of Armbian for RPI4 it seems.

Any further pointers? Thanks.

br,
 Ruben

Log from Focal based Armbian:

```me@me-ThinkCentre-M720s:~/Downloads$ ssh me@192.168.100.117
me@192.168.100.117's password: 
 ____                 _                            ____  _   _  _   
|  _ \ __ _ ___ _ __ | |__   ___ _ __ _ __ _   _  |  _ \(_) | || |  
| |_) / _` / __| '_ \| '_ \ / _ \ '__| '__| | | | | |_) | | | || |_ 
|  _ < (_| \__ \ |_) | |_) |  __/ |  | |  | |_| | |  __/| | |__   _|
|_| \_\__,_|___/ .__/|_.__/ \___|_|  |_|   \__, | |_|   |_|    |_|  
               |_|                         |___/                    
Welcome to Armbian 22.02.0-trunk.0005 Focal with bleeding edge Linux 5.15.13-bcm2711

No end-user support: untested automated build

System load:   21%           	Up time:       4 min	
Memory usage:  10% of 1.63G  	IP:	       192.168.100.117
CPU temp:      47°C           	Usage of /:    31% of 6.8G   	

[ 0 security updates available, 12 updates total: apt upgrade ]
Last check: 2022-01-09 10:33

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

me@rpi4b:~$ sudo su
[sudo] password for me: 
root@rpi4b:/home/me# apt update
Hit:1 http://ports.ubuntu.com focal InRelease
Hit:2 http://ports.ubuntu.com focal-security InRelease
Get:3 http://ports.ubuntu.com focal-updates InRelease [114 kB]           
Get:4 http://ports.ubuntu.com focal-backports InRelease [108 kB]               
Get:5 https://imola.armbian.com/beta focal InRelease [26.8 kB]                 
Get:6 http://ports.ubuntu.com focal-updates/main armhf Packages [1,119 kB]
Get:7 http://ports.ubuntu.com focal-updates/universe arm64 Packages [1,055 kB]
Get:8 http://ports.ubuntu.com focal-updates/main arm64 Packages [1,288 kB]
Get:9 http://ports.ubuntu.com focal-updates/universe armhf Packages [917 kB]
Get:10 https://imola.armbian.com/beta focal/main arm64 Packages [190 kB]       
Get:11 http://ports.ubuntu.com focal-backports/universe arm64 Packages [22.1 kB]
Get:12 http://ports.ubuntu.com focal-backports/universe armhf Packages [22.1 kB]
Fetched 4,862 kB in 2s (2,004 kB/s)                                            
Reading package lists... Done
Building dependency tree       
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@rpi4b:/home/me# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libnss-myhostname libpam-systemd libsystemd0 libudev1 linux-libc-dev
  openssh-client openssh-server openssh-sftp-server systemd systemd-sysv
  u-boot-tools udev
12 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,736 kB of archives.
After this operation, 12.3 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 http://ports.ubuntu.com focal-updates/main arm64 systemd-sysv arm64 245.4-4ubuntu3.14 [10.3 kB]
Get:2 http://ports.ubuntu.com focal-updates/main arm64 libpam-systemd arm64 245.4-4ubuntu3.14 [175 kB]
Get:3 http://ports.ubuntu.com focal-updates/main arm64 udev arm64 245.4-4ubuntu3.14 [1,320 kB]
Get:4 http://ports.ubuntu.com focal-updates/main arm64 libudev1 arm64 245.4-4ubuntu3.14 [71.2 kB]
Get:5 http://ports.ubuntu.com focal-updates/main arm64 systemd arm64 245.4-4ubuntu3.14 [3,495 kB]
Get:6 https://imola.armbian.com/beta focal/main arm64 linux-libc-dev arm64 22.02.0-trunk.0004 [1,180 kB]
Get:7 http://ports.ubuntu.com focal-updates/main arm64 libsystemd0 arm64 245.4-4ubuntu3.14 [248 kB]
Get:8 http://ports.ubuntu.com focal-updates/main arm64 openssh-sftp-server arm64 1:8.2p1-4ubuntu0.4 [48.3 kB]
Get:9 http://ports.ubuntu.com focal-updates/main arm64 openssh-server arm64 1:8.2p1-4ubuntu0.4 [354 kB]
Get:10 http://ports.ubuntu.com focal-updates/main arm64 openssh-client arm64 1:8.2p1-4ubuntu0.4 [637 kB]
Get:11 http://ports.ubuntu.com focal-updates/main arm64 u-boot-tools arm64 2021.01+dfsg-3ubuntu0~20.04.4 [156 kB]
Get:12 http://ports.ubuntu.com focal-updates/main arm64 libnss-myhostname arm64 245.4-4ubuntu3.14 [40.8 kB]
Fetched 7,736 kB in 2s (3,195 kB/s)           
Preconfiguring packages ...
(Reading database ... 43665 files and directories currently installed.)
Preparing to unpack .../systemd-sysv_245.4-4ubuntu3.14_arm64.deb ...
Unpacking systemd-sysv (245.4-4ubuntu3.14) over (245.4-4ubuntu3.13) ...
Preparing to unpack .../libpam-systemd_245.4-4ubuntu3.14_arm64.deb ...
Unpacking libpam-systemd:arm64 (245.4-4ubuntu3.14) over (245.4-4ubuntu3.13) ...
Preparing to unpack .../udev_245.4-4ubuntu3.14_arm64.deb ...
Unpacking udev (245.4-4ubuntu3.14) over (245.4-4ubuntu3.13) ...
Preparing to unpack .../libudev1_245.4-4ubuntu3.14_arm64.deb ...
Unpacking libudev1:arm64 (245.4-4ubuntu3.14) over (245.4-4ubuntu3.13) ...
Setting up libudev1:arm64 (245.4-4ubuntu3.14) ...
(Reading database ... 43665 files and directories currently installed.)
Preparing to unpack .../systemd_245.4-4ubuntu3.14_arm64.deb ...
Unpacking systemd (245.4-4ubuntu3.14) over (245.4-4ubuntu3.13) ...
Preparing to unpack .../libsystemd0_245.4-4ubuntu3.14_arm64.deb ...
Unpacking libsystemd0:arm64 (245.4-4ubuntu3.14) over (245.4-4ubuntu3.13) ...
Setting up libsystemd0:arm64 (245.4-4ubuntu3.14) ...
(Reading database ... 43665 files and directories currently installed.)
Preparing to unpack .../0-openssh-sftp-server_1%3a8.2p1-4ubuntu0.4_arm64.deb ...
Unpacking openssh-sftp-server (1:8.2p1-4ubuntu0.4) over (1:8.2p1-4ubuntu0.3) ...
Preparing to unpack .../1-openssh-server_1%3a8.2p1-4ubuntu0.4_arm64.deb ...
Unpacking openssh-server (1:8.2p1-4ubuntu0.4) over (1:8.2p1-4ubuntu0.3) ...
Preparing to unpack .../2-openssh-client_1%3a8.2p1-4ubuntu0.4_arm64.deb ...
Unpacking openssh-client (1:8.2p1-4ubuntu0.4) over (1:8.2p1-4ubuntu0.3) ...
Preparing to unpack .../3-linux-libc-dev_22.02.0-trunk.0004_arm64.deb ...
Unpacking linux-libc-dev:arm64 (22.02.0-trunk.0004) over (21.08.6) ...
Preparing to unpack .../4-u-boot-tools_2021.01+dfsg-3ubuntu0~20.04.4_arm64.deb ...
Unpacking u-boot-tools (2021.01+dfsg-3ubuntu0~20.04.4) over (2021.01+dfsg-3ubuntu0~20.04.3) ...
Preparing to unpack .../5-libnss-myhostname_245.4-4ubuntu3.14_arm64.deb ...
Unpacking libnss-myhostname:arm64 (245.4-4ubuntu3.14) over (245.4-4ubuntu3.13) ...
Setting up openssh-client (1:8.2p1-4ubuntu0.4) ...
Setting up linux-libc-dev:arm64 (22.02.0-trunk.0004) ...
Setting up systemd (245.4-4ubuntu3.14) ...
Setting up udev (245.4-4ubuntu3.14) ...
update-initramfs: deferring update (trigger activated)
Setting up libnss-myhostname:arm64 (245.4-4ubuntu3.14) ...
Setting up u-boot-tools (2021.01+dfsg-3ubuntu0~20.04.4) ...
Setting up openssh-sftp-server (1:8.2p1-4ubuntu0.4) ...
Setting up systemd-sysv (245.4-4ubuntu3.14) ...
Setting up openssh-server (1:8.2p1-4ubuntu0.4) ...
rescue-ssh.target is a disabled or a static unit, not starting it.
Setting up libpam-systemd:arm64 (245.4-4ubuntu3.14) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Processing triggers for initramfs-tools (0.136ubuntu6.6) ...
update-initramfs: Generating /boot/initrd.img-5.15.13-bcm2711
Using DTB: bcm2711-rpi-4-b.dtb
Installing /etc/flash-kernel/dtbs/bcm2711-rpi-4-b.dtb into /boot/dtbs/5.15.13-bcm2711/./bcm2711-rpi-4-b.dtb
Taking backup of bcm2711-rpi-4-b.dtb.
Installing new bcm2711-rpi-4-b.dtb.
Ignoring old or unknown version 5.15.13-bcm2711 (latest is )
root@rpi4b:/home/me# 
root@rpi4b:/home/me# 
root@rpi4b:/home/me# apt install -y git dialog build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dialog is already the newest version (1.3-20190808-1).
git is already the newest version (1:2.25.1-1ubuntu3.2).
build-essential is already the newest version (12.8ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@rpi4b:/home/me# git clone https://gitlab.com/bashrc2/libreserver
Cloning into 'libreserver'...
warning: redirecting to https://gitlab.com/bashrc2/libreserver.git/
remote: Enumerating objects: 4395, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 4395 (delta 42), reused 13 (delta 6), pack-reused 4189
Receiving objects: 100% (4395/4395), 42.58 MiB | 10.84 MiB/s, done.
Resolving deltas: 100% (2559/2559), done.
root@rpi4b:/home/me# cd libreserver/
root@rpi4b:/home/me/libreserver# git checkout bullseye
Already on 'bullseye'
Your branch is up to date with 'origin/bullseye'.
root@rpi4b:/home/me/libreserver# make install
mkdir -p /usr/local/bin
mkdir -p /usr/share/libreserver/base
mkdir -p /usr/share/libreserver/apps
mkdir -p /usr/share/libreserver/android-app
mkdir -p /usr/share/libreserver/webadmin
mkdir -p /usr/share/libreserver/utils
mkdir -p /usr/share/libreserver/avatars
mkdir -p /etc/libreserver
cp src/libreserver /usr/local/bin
rm -f /usr/local/bin/libreserver-*
cp -r image_build/* /etc/libreserver
cp img/avatars/* /usr/share/libreserver/avatars
cp src/view-x-face /usr/local/bin
cp src/muttquote-x-face /usr/local/bin
cp src/* /usr/local/bin
cp src/libreserver-mesh-batman /usr/local/bin/batman
cp src/libreserver-backup-local /usr/local/bin/backup
cp src/libreserver-backup-local /usr/local/bin/backup2friends
cp src/libreserver-restore-local /usr/local/bin/restore
rm -f /usr/share/libreserver/base/*
rm -f /usr/share/libreserver/apps/*
rm -f /usr/share/libreserver/utils/*
mv /usr/local/bin/libreserver-base-* /usr/share/libreserver/base
mv /usr/local/bin/libreserver-app-* /usr/share/libreserver/apps
mv /usr/local/bin/libreserver-utils-* /usr/share/libreserver/utils
mkdir -m 755 -p /usr/local/share/man/man1
cp man/libreserver.1.gz /usr/local/share/man/man1
rm /usr/local/share/man/man1/libreserver*.1.gz
cp man/*.1.gz /usr/local/share/man/man1
cp man/libreserver-backup-local.1.gz /usr/local/share/man/man1/backup.1.gz
cp man/libreserver-restore-local.1.gz /usr/local/share/man/man1/restore.1.gz
cp img/android-app/*.png /usr/share/libreserver/android-app
cp -r webadmin/* /usr/share/libreserver/webadmin
chown -R root: /usr/share/libreserver
chown root: /usr/local/bin/libreserver*
chmod -R +r /usr/share/libreserver
cp src/libreserver-email-remove-html /usr/bin/remove_html
mkdir -p /etc/share/distro-info
/usr/local/bin/libreserver-prepare-scripts
root@rpi4b:/home/me/libreserver# adduser admin
Adding user `admin' ...
Adding new group `admin' (1001) ...
Adding new user `admin' (1001) with group `admin' ...
Creating home directory `/home/admin' ...
Copying files from `/etc/skel' ...
New password: 
Retype new password: 
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
	Full Name []: admin
	Room Number []: 
	Work Phone []: 
	Home Phone []: 
	Other []: 
Is the information correct? [Y/n] y
root@rpi4b:/home/me/libreserver# libreserver menuconfig --noninteractive
You should only run this on a Debian Buster based system
root@rpi4b:/home/me/libreserver# 
```

**Comment by bashrc2** [comment]
LibreServer should not install on any distro other than Debian 11 (bullseye). Raspbian and the Armbian version of Debian are sufficiently close that they also work.

However, this highlights a problem with the "just install Armbian" mantra. Armbian ships ubuntu and still calls it Armbian. Ubuntu is debian based, but it's not the same thing.

For Rpi I have recently made a Raspbian image which should install. See https://libreserver.org/downloads

**Comment by ruben-s** [comment]
Hi,

Thank you for your reply.

After my comment I investigated the libreserve script (https://github.com/bashrc2/libreserver/blob/bullseye/src/libreserver).
In there I can indeed see there is a check on distro which does not match for Armbian on RPI as Armbian for RPI is based on Ubuntu.

However I did see that the distro check also caters for "raspbian".
So I followed the https://libreserver.org/armbian.html guide but substituting the Armbian for Raspbian (i.e. I installed Raspbian on the RPI4).

This works to some extent:
When coming to the stage of running the command "libreserver menuconfig --noninteractive" it does not work.
The script exits with a message 'no domain given' or such thing (possibly because I did not configure wifi, as I manully configured eth on rasbian?).

If I run "libreserver menuconfig" and step through the menus then the install runs and exists apparently ok. 

However after logging on to the web admin console as admin, the webpages for "apps" and "members" result in a 404.
The rest of the pages seem to be working (e.g. settings, backup, ...).
However as Apps does not work, I've not yet come to a working server.

Another remark: at the end in the installation script an IP address is shown on which to connect to the web admin console.
However the IP address shown does not match the static ip that is configured in /etc/dhcpcd.conf.
It seems libreserver is configuring /etc/network/interfaces.d directly (file dynamic), and shows the resulting ip address of a dhcp request? 
A dynamic ip address is a bit counterintuitive for a server, no?
Strangely enough the ip address shown is not visible in ifconfig, so I need to connect to the configured static ip.

Any ideas on getting "Apps" to work?

Thanks

br,
 Ruben

**Comment by bashrc2** [comment]
This works to some extent:

>
>
>  When coming to the stage of running the command "libreserver menuconfig --noninteractive" it does not work.
>  The script exits with a message 'no domain given' or such thing (possibly because I did not configure wifi, as I manully configured eth on rasbian?).
>
>
>
> If I run "libreserver menuconfig" and step through the menus then the install runs and exists apparently ok.
>
>

I've removed the noninteractive option from the documentation. That only works if you have a pre-existing configuration file.


>
>
> However after logging on to the web admin console as admin, the webpages for "apps" and "members" result in a 404.
>  The rest of the pages seem to be working (e.g. settings, backup, ...).
>  However as Apps does not work, I've not yet come to a working server.
>
>
>
>
> Another remark: at the end in the installation script an IP address is shown on which to connect to the web admin console.
>  However the IP address shown does not match the static ip that is configured in /etc/dhcpcd.conf.
>  It seems libreserver is configuring /etc/network/interfaces.d directly (file dynamic), and shows the resulting ip address of a dhcp request?
>  A dynamic ip address is a bit counterintuitive for a server, no?
>  Strangely enough the ip address shown is not visible in ifconfig, so I need to connect to the configured static ip.
>
>
>

This looks like something specific to Raspbian. I've added something to detect the dhcpcd daemon and disable it so that it doesn't interfere with any other settings.

Dynamic IP address is the expected situation. Very few people have a static external IP address. When you forward ports from your router it will typically use the mac address of the Rpi to ensure that the forward works even if it is later assigned a different internal IP address.

- Bob

**Comment by ruben-s** [comment]
Hi Bob,

Thanks again. Any feedback on getting the apps.html to work?
I did not find an apps.html file in /var/www/foo.local/htdocs/admin.
Others (e.g. settings.html) are present. Or is the ./admin/apps.html link obsolete, i.e. should be a different link?

I've checked the Makefile but could not immediately find where these *.html files are either generated or copied from.
Is this an issue with the bullseye branch or something else?

With respect to the static/dynamic ip address: indeed I fully agree that most people do not have a static public ip address available. Then again, I don't think that most people will have the libreserver connected directly to their ISP/public internet. 

Most likely a router/modem will in between which needs to provide the port mapping from the dynamic public ip of the modem/router to an internal [target].

As to the port mapping: my cisco does not allow to map a port directly to a mac address.
If I would want to follow your scenario I need to first to use DHCP of the cisco to map the mac address of the RPI to a dhcp assigned "static" ip address, and then add a port mapping rule to map the 80/443 port to this dhcp assigned internal static ip.
Personally I find it easier to give my "servers"  a static local ip address outside the dhcp range and only do the port mapping in the router/modem.
So far I've never seen a router/modem that allows a direct mapping of port to a mac address.

If indeed your assumption is that the libreserver needs a dynamicly assigned internal ip address then this should be mentioned somewhere in the docs? So people know how to configure their router/modem accordingly.
My preferred solution would be for the user to select the way of working (dynamic / static) in the set-up script.

Any pointers on the apps.html issue will be appreciated.

br,
 Ruben

**Comment by bashrc2** [comment]
Thanks again. Any feedback on getting the apps.html to work?

>
>
>  I did not find an apps.html file in /var/www/foo.local/htdocs/admin.
>  Others (e.g. settings.html) are present. Or is the ./admin/apps.html link obsolete, i.e. should be a different link?
>
>
>

The apps files are generated. You can run libreserver-upgrade and it will regenerate any missing html files. Ordinarily that would happen during the install.


>
>
> As to the port mapping: my cisco does not allow to map a port directly to a mac address.
>
>
>
>
>  If I would want to follow your scenario I need to first to use DHCP of the cisco to map the mac address of the RPI to a dhcp assigned "static" ip address, and then add a port mapping rule to map the 80/443 port to this dhcp assigned internal static ip.
>  Personally I find it easier to give my "servers"  a static local ip address outside the dhcp range and only do the port mapping in the router/modem.
>  So far I've never seen a router/modem that allows a direct mapping of port to a mac address.
>
>
>
You can set up a static local IP address from the control panel. Log in via ssh, then sudo su, then "control".

The association of forwards to devices by their mac address is usually possible with OpenWrt based routers.

- Bob

**Comment by ruben-s** [comment]
Hi Bob,

thanks for your help.

I've run the libreserver-upgrade both on the command line and via the control ascii menu.
Yet the apps.html is not being generated (I've also installed the pi-hole app via the ascii control menu, still no apps.html page).
I could not find any logs in /var/log directly related to libreserver.

When I navigate to http://[libreserver ip]/home I get a page "no apps installed".
When I use the control ascii menu I can see pihole and configure it. I could not make out on which port the pihole admin page is available.

I'm going to stop at this point.
For the moment I'm going to just install pi-hole native on raspian and revisit your project later.
I had hoped to use some other apps in the list (syncting, xmpp, etesync - to replace radicale), but I'll have to install them myself along the pihole project.

Thanks again.

br,
 Ruben
